### PR TITLE
Added test-only NullHtmlWriter and Deferred

### PR DESCRIPTION
**Pull request by jnorthrup**
tested a few things with the linux native performance.  deferred writer just wraps all writer ops into a delegate lambda, unconcerned with the eventual output toString() (it's likely rubbish in all cases where the delegate is not writing to a sequential sink)

no commentary on OO encapuslation here, i appear to have exposed some privates in the name of inline methods, and that completely hammered performance.  did not make them private again.  unintentional commit of the java benchmark.

in summary:  the pre-write overhead seems high for the purposes of signalling indents, pointers to constant strings, and concatenating them.

the post-write string appenders don't appear to cost as much benchmark time as the creation event of wrapping them in the lambda.  this surprises me because compilers can see where and when lambdas are created and work backwards,  but is not expected to do as well at optimizing the actual call-site of a lambda in a perfect smalltalk world.    for hotspot this is probably a minor warm-up blip on the timeline with no consequence.  likewise, we can't say that this native compilation is doing -O6 -lto on my setup, but finding a reference to those llvm switches would make an interesting followup  

for native:
---
baseline SimpleBenchmark
Iteration Took 3925 millis. Count: 154340000
Benchmark Completed. Benchmark Total Millis: 207804, Average iteration was 4155.96 millis

DeferredBenchmark:
Iteration Took 29691 millis. Count: 1060000; Creation 19299.0; Reify 10376.0; r/c = 0.53

NullBenchmark: 795 millis

### CODE REVIEW

**Comment by jnorthrup** [comment]
circle-ci is sure taking its time here.  maybe you need to add some more quarters...

**Comment by ScottPierce** [comment]
Interesting. I think the main take-away for me is that Kotlin/native just has garbage performance right now for object creation. I wonder if it's the same for Swift, and other native languages.

Good idea with the null writer to just see the actual overhead of the operations. Probably the most interesting thing is even when writing nothing - the benchmark still takes more than twice as long as the JVM.

**Comment by ScottPierce** [comment]
CircleCI won't run on PRs from other repos - otherwise they'd be able to modify the build script and extract build secrets.

**Comment by jnorthrup** [comment]
i ported a russian rope implementation to kotlin.   https://github.com/jnorthrup/rope  googling around it looks like the stringbuilder is faster until you create huge strings and cross threshold of appending large gc objects, so im in no rush here to test this out.  im not sure what mojo needs to be done to port the simpletest kotlin file to jvm i have up until now been trying to steer clear of the frikken gradle magic.

**Comment by jnorthrup** [comment]
there are apparently ways to insert llvm flags into the native build but inserting "-opt" into the jvm relvent flags you have there is not one of them.

there's not a a lot of optimized native examples in google that i have discovered, and i have yet to hear a response to my inquiry on slack to this effect.

**Comment by ScottPierce** [comment]
>frikken gradle magic

Gradle is the future on JVM man. Gotta just lean into it.

I was told by a JB employee that if I run a release built for kotlin/native that it applies the `-opt` command automatically.

**Comment by jnorthrup** [comment]
> I was told by a JB employee that if I run a release built for kotlin/native that it applies the -opt command automatically.

appears true

`
Iteration Took 11564 millis. Count: 154340000
Benchmark Completed. Benchmark Total Millis: 598882, Average iteration was 11977.64 millis
DeferredBenchmark start
Iteration Took 51389 millis. Count: 1060000; Creation 28201.0; Reify 23146.0; r/c = 0.8207510371972625
`
 >> frikken gradle magic

 >  Gradle is the future on JVM man. Gotta just lean into it.

there's gradle, and there's a gradle learning curve, but my reference was to tmfm specifically, and enduring the Rex Kwon Doe 8 week course in kotlin mutliplatform... https://www.youtube.com/watch?v=q_W4Gi5h9P8

**Comment by jnorthrup** [comment]
i noticed that there was no simple mapping to bytearray from CharSequence and the lightbulb clicked on. 
 ratther than rely on String as a Utility, just keep the const string pointers you already get for free in the compiler.

Iteration Took 2521 millis. Count: 154340000
Benchmark Completed. Benchmark Total Millis: 123772, Average iteration was 2475.44 millis
DeferredBenchmark start
Iteration Took 30603 millis. Count: 1060000; Creation 20816.0; Reify 9778.0; r/c = 0.4697348193697156

**Comment by ScottPierce** [comment]
So by altering `CharSequence` to use `String` instead - you've made the performance significantly better? This sounds like something that I should file as a Kotlin/native improvement. Can you help me understand why this improves things?

**Comment by jnorthrup** [comment]
the compiler inserts pointers to strings, or string vtables, and your code erases those and forces iterators

**Comment by ScottPierce** [comment]
I made a bug for the Kotlin/native team to comment on: https://github.com/JetBrains/kotlin-native/issues/3200

**Comment by jnorthrup** [comment]
i think this is likely in the "wontfix" purvue judging by the big disclaimer in Charsequence jdk docs.   

> do not use as keys or equality bearing objects. 

CharArray and CharSequence are two completely different looking animals.  kotlinc may be erring on the side of safety by not exposing the underlying String to SringBuilder when it calls toString() and allowing for an impl related optimization to make a typecheck that native kotlin may not consider important at this stage.

**Comment by ScottPierce** [comment]
You might be right. Either way - I learn something new about this strange new native world I've stepped into.

**Comment by jnorthrup** [comment]
the performance of unsigned *byte in C will effectively be the performance wall you can't pass.  using java-based types will force you to have signed bytes, but you will still be able to perform bulk array operations relatively quickly until you care about the high bit.  the compiler may recognize you adding "&0xff" in java and specialize the instructions but it really pollutes the code.   

in java, sometimes the native impl of ByteBuffer will enable an optimal instructionset for what you're doing here.  there is not hard fast rule for which version of java and which version of Heap or Direct Mmemory performs best for a given operation.  Stringbuilder is optimal in some pretty old tests of rope classes, and the rope classes in questions may also be pretty far from optimal.  if you know you have JVM target, use Javolution Text or even the javolution XML libraries as these are targetted for hard-realtime embedded profiles and tend to do extremly well in all cases.

kotlin native is definitely awful performance as of this PR.

**Comment by jnorthrup** [comment]
this pr seems to have run its course. cheers

**Comment by ScottPierce** [comment]
Thanks Jim :)

**Pull request closed without merging**
